# -*- coding: utf-8 -*-
"""Week5ComparingData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17afHhQsHjnNE0XIXjDVuKR7WSOiWC4aF
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/inside_data.csv")
df.head ()
print(df.columns)
print(df.head())

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/outside_data.csv")
df.head ()
print(df.columns)
print(df.head())

import pandas as pd
import matplotlib.pyplot as plt

#inside_data
inside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/inside_data.csv")
inside_time_series = inside_df.columns[0]
inside_df[inside_time_series] = pd.to_datetime(inside_df[inside_time_series])

plt.figure(figsize=(10, 6))
plt.plot(inside_df[inside_time_series], inside_df.iloc[:, 1])
plt.title('Inside Data Time Series')
plt.xlabel('Time')
plt.ylabel('Data')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

#outside_data
outside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/outside_data.csv")
outside_time_series = outside_df.columns[0]
outside_df[outside_time_series] = pd.to_datetime(outside_df[outside_time_series])

plt.figure(figsize=(10, 6))
plt.plot(outside_df[outside_time_series], outside_df.iloc[:, 1])
plt.title('Outside Data Time Series')
plt.xlabel('Time')
plt.ylabel('Data')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load inside_data
inside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/inside_data.csv")
inside_time_series = inside_df.columns[0]  # Assuming the first column is time series data
inside_df[inside_time_series] = pd.to_datetime(inside_df[inside_time_series])

# Load outside_data
outside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/outside_data.csv")
outside_time_series = outside_df.columns[0]  # Assuming the first column is time series data
outside_df[outside_time_series] = pd.to_datetime(outside_df[outside_time_series])

# Plot both inside and outside data
plt.figure(figsize=(10, 6))

plt.plot(inside_df[inside_time_series], inside_df.iloc[:, 1], label='Inside Data')
plt.plot(outside_df[outside_time_series], outside_df.iloc[:, 1], label='Outside Data')

plt.title('Inside and Outside Data Time Series')
plt.xlabel('Time')
plt.ylabel('Data')
plt.grid(True)
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


inside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/inside_data.csv")


outside_df = pd.read_csv("https://raw.githubusercontent.com/KevinTruong02/E11-Lab-Kevin-Ryan-Nick/main/outside_data.csv")


plt.figure(figsize=(10, 6))


plt.hist(inside_df.iloc[:, 1], bins=20, alpha=0.5, label='Inside Data')
plt.hist(outside_df.iloc[:, 1], bins=20, alpha=0.5, label='Outside Data')

plt.title('Histograms of Inside and Outside Data')
plt.xlabel('Data')
plt.ylabel('Frequency')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

"""a. When comparing the two sets of data, it is shown that the inside data not starting until ~ 23 where at ~ 23, the frequency immediately increase to ~85Hz and continously increase until data reached to ~24 where the histogram stopped, ending at ~ 23.8 with the frequency of ~ 270 hz. The histogram for outside data started very high at ~ 17.8 and with a frequency ~180 but after passing ~18.0, the frequency data started to decrease continously, ending at ~24.5

b. The data are statistically different since the mean for the inside data is ~ 23.6 while the outside data is 19.34. The uncertainty of inside mean is 0.036 while outside is 0.122 which would lead the standard devaition to be more than 3, being 33.35 standard deviation.
"""

import numpy as np


inside_mean = inside_df.iloc[:, 1].mean()
inside_std = inside_df.iloc[:, 1].std()
inside_N = len(inside_df)
inside_sigma_mean = inside_std / np.sqrt(inside_N)


outside_mean = outside_df.iloc[:, 1].mean()
outside_std = outside_df.iloc[:, 1].std()
outside_N = len(outside_df)
outside_sigma_mean = outside_std / np.sqrt(outside_N)

separation = np.abs(inside_mean - outside_mean) / np.sqrt(inside_sigma_mean**2 + outside_sigma_mean**2)
is_statistically_different = separation > 3

print("Means:")
print("Inside Data Mean:", inside_mean)
print("Outside Data Mean:", outside_mean)
print("\nUncertainty on the Mean:")
print("Inside Data Sigma Mean:", inside_sigma_mean)
print("Outside Data Sigma Mean:", outside_sigma_mean)
print("\nSeparation (in terms of standard deviations):", separation)
print("Are the means statistically different?", is_statistically_different)
