# -*- coding: utf-8 -*-
"""week5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5sWukFavH0N2AdJTRK57OY67ZrGyor6
"""

import sys
import random
import time
import csv


print(sys.argv)

start_time = time.time()
run_time = 10
if len(sys.argv) > 1:
  run_time = int(sys.argv[1])
now = start_time

filename = "test_data.csv"
if len(sys.argv) > 2:
  filename = sys.argv[2]
file = open(filename, "w", newline='')
writer = csv.writer(file)

meta_data = ["Time", "Data"]
writer.writerow(meta_data)
print(meta_data)

while (now-start_time)< run_time:
  time.sleep(1)
  data= random.random()
  now= time.time()
  data_list = [now,data]
  print(data_list)
  writer.writerow(data_list)



